[module/battery]
type = custom/script
exec = $HOME/.config/polybar/script/battery.sh

;echo hello world

format = <label>
format-padding = 2

label = %output%
label-background = ${color.layer2}
label-underline = ${color.neon-br3}
label-padding = 2

tail = true

#internal = 60
