[module/cpu]
type = internal/cpu
interval = 0.5
warn-percentage = 95
#offset-y = 10%
#offset-x = 10%

format = <label>
format-prefix = %{T3}󰻠 %{T-}
format-background = ${color.layer2}
format-underline = ${color.neon-br-pr3}
format-padding = 2

label = %{F#fff}%percentage%%{F-}%

