[module/cpu]
type = internal/cpu
interval = 0.5
warn-percentage = 95
#offset-y = 10%
#offset-x = 10%

format = <label>
format-padding = 1

label-background = ${color.layer2}
label-underline = ${color.neon-br-pr3}
label-padding = 2

label =  %{T2} %{T-}%{F#fff}%percentage%%{F-}%

