[module/date]
type = internal/date
interval = 1.0
time = %H:%M %p

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
;;date-alt = %A, %d %B %Y
#time-alt = %d/%m/%Y%
time-alt =  %b %d %G
format = <label>
format-prefix = " "
format-font = 2
; format-prefix-foreground = ${color.CYAN}
format-padding = 0
format-underline = #fff
label = %time%
