[module/demo]
type = custom/text
label-wow = "Custom Label Content"
format = <label-wow>
; type = custom/ipc
; hook-0 = echo foobar
; hook-1 = date +%s
; hook-2 = whoami
; format = <label>
; format-1 = <label>
; format-1-background = #ff0000
; initial = 1
; click-left = "#demo.hook.0"
; click-right = "#demo.hook.1"
; double-click-left = "#demo.hook.2"
