; [global/wm]
; include-file= ~/.config/polybar/custom/defineData.ini

[item]
icon=""
act=""

[module/hlwm]
type = internal/xworkspaces

pin-workspaces = false
; group-by-monitor = false
enable-click = true
enable-scroll = true
reverse-scroll = true
index-sort = true

format = %{T3}<label-state>%{T-}

label-active = ${item.act}
label-active-foreground = ${color.layer4}
label-active-background = ${color.layer2}
label-active-underline = ${color.layer3}

label-occupied = ${item.icon}
label-occupied-foreground = ${color.layer3}
label-occupied-underline = ${color.layer4}

label-urgent = ${item.icon}
label-urgent-foreground = ${color.layer3}

label-empty = ${item.icon}
label-empty-foreground = ${color.layer3}

label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1
