[module/memory]
type = custom/ipc
hook-0 = read-memory -nm
hook-1 = read-memory -ns

format = <label>
format-padding = 2
format-padding-right = 2
radius = 6.0


label = %{F#00C0F9}%{T3}%{T-}%{F-} %{F#fff}%output%%{F-}
label-underline = ${color.neon-br3}
label-background = ${color.layer2}
label-padding = 1


initial = 1 
click-left = "#memory.hook.0"
click-right = "#memory.hook.1"

; type = internal/memory
; interval = 3
; warn-percentage = 95
; format = <label>
; label = %{F#fff}%{T3}%{T-}%{F-}:%gb_used%
; label-padding = 3
