[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout> 
;<label-indicator>
format-background = ${color.layer2}
format-underline = ${color.neon-br-pr3}
format-spacing = 0

label-layout = %layout%
label-layout-padding = 2
; label-layout-background = #bc99ed
; label-layout-foreground = #000

